In [20]:
word = "abcd" #-> "A-Bb-Ccc-Dddd"
#accum("RqaEzty") #-> "R-Qq-Aaa-Eeee-Zzzzz-Tttttt-Yyyyyyy"
#accum("cwAt") #-> "C-Ww-Aaa-Tttt"

new_lst = []

for letter, index in zip(word, range(len(word))):
    upper = letter.upper()
    lower = letter*index
    new_lst.append(upper + lower)
    
"-".join(new_lst)


'R-Qq-Aaa-EEEE-Zzzzz-Tttttt-Yyyyyyy'

In [ ]:
#def accum(s):



In [22]:
import numpy as np

In [36]:
a = np.array([1,2,3,4,5])

print(np.zeros(5))
print(np.zeros((3,2)))
print(np.zeros((3,2), dtype=int))

#Dá a quantidade de dados tendo em conta a fonte onde vai buscar os dados
print(np.zeros_like(()))

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]
 [0 0]]
0


In [33]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
a.shape

(5,)

In [37]:
np.random.random(5)

array([0.28743264, 0.0290291 , 0.69791205, 0.85813982, 0.10176151])

In [39]:
np.arange(2,100)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
b = np.linspace(5.0, 500, 10)
b

array([  5.,  60., 115., 170., 225., 280., 335., 390., 445., 500.])

In [45]:
x = np.array([[1],2,[3,3.5],4,5])
print(x[0])
print(x[0][0])
print(x[2][1])

a = np.array([0,2])

print(x[a])

[1]
1
3.5
[list([1]) list([3, 3.5])]


In [50]:
x = np.arange(20)*2
print(x)

condition = x < 5
print(condition)
x[condition]


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[ True  True  True False False False False False False False False False
 False False False False False False False False]


array([0, 2, 4])

In [56]:
array = np.random.random((5,4))

print(array)

print(array.max())
print(array.mean())
print(array.max(axis = 1)) #rows
print(array.max(axis = 0)) #column

[[0.54528519 0.69528791 0.11936258 0.76028833]
 [0.21990584 0.20758986 0.86811194 0.42691883]
 [0.89046593 0.58734173 0.99253355 0.50505556]
 [0.78170656 0.4004719  0.6769221  0.28818881]
 [0.62469059 0.40744075 0.42155601 0.26880655]]
0.9925335469612631
0.5343965259648964
[0.76028833 0.86811194 0.99253355 0.78170656 0.62469059]
[0.89046593 0.69528791 0.99253355 0.76028833]


In [59]:
array.mean(axis = 1)

array([0.530056  , 0.43063162, 0.74384919, 0.53682234, 0.43062347])

In [58]:
np.square(array)

array([[0.29733594, 0.48342527, 0.01424743, 0.57803834],
       [0.04835858, 0.04309355, 0.75361835, 0.18225968],
       [0.79292958, 0.34497031, 0.98512284, 0.25508112],
       [0.61106514, 0.16037774, 0.45822353, 0.08305279],
       [0.39023833, 0.16600797, 0.17770947, 0.07225696]])

In [ ]:
#numpy vectorize
#advanced topic

